version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=thalison
            - MYSQL_DATABASE=thalison
            - MYSQL_USER=thalison
            - MYSQL_PASSWORD=thalison
        ports:
            - '3304:3306'
